[[services]]
type = "web"
name = "hsconsulting"
runtime = "python"
buildCommand = "pip install -r requirements.txt"
startCommand = "bash build.sh && python manage.py setup_admin && gunicorn config.wsgi:application"
region = "eu"
plan = "hobby"

[[services]]
type = "postgres"
name = "hsconsulting-db"
plan = "hobby"
region = "eu"
databaseName = "hsconsulting_db"

