[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate && gunicorn config.wsgi:application"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
