services:
  - type: web
    name: hsconsulting
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: python render_hard_reset.py && gunicorn config.wsgi:application --log-file - --timeout 600
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "hsconsulting.onrender.com"
      - key: PYTHON_VERSION
        value: "3.14.3"
