services:
  - type: web
    name: hsconsulting
    runtime: python
    buildCommand: bash -c 'pip install -r requirements.txt && python manage.py migrate --noinput && python render_hard_reset.py && python manage.py collectstatic --noinput --clear'
    startCommand: gunicorn config.wsgi:application --log-file - --timeout 600 --workers 2
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "hsconsulting.onrender.com"
      - key: PYTHON_VERSION
        value: "3.14.3"
