# Generated by Django 4.2.11 on 2026-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    # The requested partner contact fields already exist in 0001_initial.
    # Keep this migration as a no-op so databases with a stale migration graph
    # can mark it applied without attempting duplicate column additions.
    operations = []
