# Generated by Django 4.2.11 on 2026-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='email_2',
            field=models.EmailField(blank=True, help_text="Second partner's email", max_length=254),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='phone_2',
            field=models.CharField(blank=True, help_text="Second partner's phone", max_length=20),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='whatsapp_2',
            field=models.CharField(blank=True, help_text="Second partner's WhatsApp", max_length=20),
        ),
    ]
