# Generated by Django 4.2.11 on 2026-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_partner_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='whatsapp_message',
            field=models.CharField(default='Hello! I would like to inquire about your services.', max_length=255),
        ),
    ]
